package com.smalltrend.service.products;

import com.smalltrend.dto.products.CreateProductComboItemRequest;
import com.smalltrend.dto.products.CreateProductComboRequest;
import com.smalltrend.dto.products.ProductComboResponse;
import com.smalltrend.entity.Product;
import com.smalltrend.entity.ProductCombo;
import com.smalltrend.entity.ProductComboItem;
import com.smalltrend.entity.ProductVariant;
import com.smalltrend.entity.Unit;
import com.smalltrend.repository.ProductComboItemRepository;
import com.smalltrend.repository.ProductComboRepository;
import com.smalltrend.repository.ProductVariantRepository;
import com.smalltrend.validation.product.ProductComboValidator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ProductComboServiceTest {

    @Mock
    private ProductComboRepository productComboRepository;

    @Mock
    private ProductComboItemRepository productComboItemRepository;

    @Mock
    private ProductVariantRepository productVariantRepository;

    @Mock
    private ProductComboValidator productComboValidator;

    @InjectMocks
    private ProductComboServiceImpl productComboService;

    private ProductCombo testCombo;
    private ProductVariant testVariant;
    private ProductComboItem testComboItem;

    @BeforeEach
    void setUp() {
        testCombo = new ProductCombo();
        testCombo.setId(1);
        testCombo.setComboCode("CB-01");
        testCombo.setComboName("Test Combo");
        testCombo.setIsActive(true);

        Product testProduct = new Product();
        testProduct.setId(10);
        testProduct.setName("Test Product");

        Unit testUnit = new Unit();
        testUnit.setId(100);
        testUnit.setName("Box");

        testVariant = new ProductVariant();
        testVariant.setId(5);
        testVariant.setSellPrice(BigDecimal.valueOf(100));
        testVariant.setProduct(testProduct);
        testVariant.setUnit(testUnit);
        testVariant.setAttributes(Map.of("Color", "Red"));
        
        testComboItem = new ProductComboItem();
        testComboItem.setId(1);
        testComboItem.setCombo(testCombo);
        testComboItem.setProductVariant(testVariant);
        testComboItem.setQuantity(2);
    }

    @Test
    void getAllCombos_shouldReturnMappedList() {
        // Arrange
        when(productComboRepository.findAll()).thenReturn(List.of(testCombo));
        when(productComboItemRepository.findByComboId(1)).thenReturn(List.of(testComboItem));

        // Act
        List<ProductComboResponse> result = productComboService.getAllCombos();

        // Assert
        assertEquals(1, result.size());
        assertEquals("Test Combo", result.get(0).getComboName());
        assertEquals(1, result.get(0).getItems().size());
        verify(productComboRepository).findAll();
        verify(productComboItemRepository).findByComboId(1);
    }

    @Test
    void getComboById_shouldThrowException_whenNotFound() {
        // Arrange
        when(productComboValidator.requireExistingCombo(99))
            .thenThrow(new RuntimeException("Không tìm thấy combo với id: 99"));

        // Act & Assert
        RuntimeException ex = assertThrows(RuntimeException.class, () -> productComboService.getComboById(99));

        assertEquals("Không tìm thấy combo với id: 99", ex.getMessage());
    }

    @Test
    void createCombo_shouldCreateSuccessfully_withAutoGeneratedCodeAndNullItems() {
        // Arrange
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboName("Auto Code Combo");
        // items is null

        ProductCombo savedCombo = new ProductCombo();
        savedCombo.setId(2);
        savedCombo.setComboCode("COMBO-DATE-001");

        // mock to simulate empty repo for code generation
        when(productComboRepository.findAll()).thenReturn(Collections.emptyList());
        when(productComboRepository.save(any(ProductCombo.class))).thenReturn(savedCombo);
        when(productComboItemRepository.findByComboId(2)).thenReturn(Collections.emptyList());

        // Act
        ProductComboResponse result = productComboService.createCombo(req);

        // Assert
        assertNotNull(result);
        assertTrue(result.getComboCode().startsWith("COMBO-"));
        verify(productComboRepository).save(any(ProductCombo.class));
    }

    @Test
    void createCombo_shouldThrowException_whenComboCodeIsDuplicate() {
        // Arrange
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboCode("DUP-123");

        doThrow(new RuntimeException("Mã combo đã tồn tại: DUP-123"))
            .when(productComboValidator).validateComboCodeUniqueForCreate("DUP-123");

        // Act & Assert
        RuntimeException ex = assertThrows(RuntimeException.class, () -> productComboService.createCombo(req));

        assertEquals("Mã combo đã tồn tại: DUP-123", ex.getMessage());
    }

    @Test
    void createCombo_shouldCalculatePriceAndSaveItems_fullyCoveringBranchLogic() {
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboCode("CB-100");
        
        CreateProductComboItemRequest itemReq = new CreateProductComboItemRequest();
        itemReq.setProductVariantId(5);
        itemReq.setQuantity(null); // falls back to 1
        itemReq.setMinQuantity(null); // falls back to 1
        itemReq.setMaxQuantity(null); // falls back to quantity
        itemReq.setIsOptional(null); // falls back to false
        itemReq.setCanSubstitute(null); // falls back to false
        itemReq.setDisplayOrder(null); // falls back to 0
        
        req.setItems(List.of(itemReq));

        when(productComboValidator.requireExistingVariant(5)).thenReturn(testVariant);
        
        ProductCombo savedCombo = new ProductCombo();
        savedCombo.setId(3);
        savedCombo.setComboCode("CB-100");
        
        when(productComboRepository.save(any(ProductCombo.class))).thenReturn(savedCombo);
        when(productComboItemRepository.findByComboId(3)).thenReturn(List.of(testComboItem));

        ProductComboResponse result = productComboService.createCombo(req);

        assertNotNull(result);
        verify(productComboItemRepository).save(any(ProductComboItem.class));
    }

    @Test
    void createCombo_shouldThrowException_whenItemVariantNotFound() {
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboCode("CB-200");
        
        CreateProductComboItemRequest itemReq = new CreateProductComboItemRequest();
        itemReq.setProductVariantId(99); 
        req.setItems(List.of(itemReq));

        when(productComboValidator.requireExistingVariant(99))
            .thenThrow(new RuntimeException("Không tìm thấy biến thể với id: 99"));

        RuntimeException ex = assertThrows(RuntimeException.class, () -> productComboService.createCombo(req));

        assertEquals("Không tìm thấy biến thể với id: 99", ex.getMessage());
    }

    @Test
    void updateCombo_shouldUpdatePerfectly() {
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboCode("CB-01"); // same code
        // No items to trigger empty items branch
        req.setItems(Collections.emptyList());

        when(productComboValidator.requireExistingCombo(1)).thenReturn(testCombo);
        when(productComboRepository.save(any(ProductCombo.class))).thenReturn(testCombo);
        when(productComboItemRepository.findByComboId(1)).thenReturn(Collections.emptyList());

        ProductComboResponse result = productComboService.updateCombo(1, req);

        assertNotNull(result);
        verify(productComboItemRepository).deleteByComboId(1);
    }

    @Test
    void updateCombo_shouldThrowException_whenDuplicateCodeOnRename() {
        CreateProductComboRequest req = new CreateProductComboRequest();
        req.setComboCode("NEW-CB");

        when(productComboValidator.requireExistingCombo(1)).thenReturn(testCombo);
        doThrow(new RuntimeException("Mã combo đã tồn tại: NEW-CB"))
            .when(productComboValidator).validateComboCodeUniqueForUpdate(testCombo, "NEW-CB");

        RuntimeException ex = assertThrows(RuntimeException.class, () -> productComboService.updateCombo(1, req));

        assertEquals("Mã combo đã tồn tại: NEW-CB", ex.getMessage());
    }

    @Test
    void deleteCombo_shouldDeleteComboAndItems() {
        when(productComboValidator.requireExistingCombo(1)).thenReturn(testCombo);

        productComboService.deleteCombo(1);

        verify(productComboItemRepository).deleteByComboId(1);
        verify(productComboRepository).delete(testCombo);
    }

    @Test
    void toggleStatus_shouldReverseIsActive() {
        when(productComboValidator.requireExistingCombo(1)).thenReturn(testCombo);
        assertTrue(testCombo.getIsActive());

        productComboService.toggleStatus(1);

        assertFalse(testCombo.getIsActive()); // it should be false now
        verify(productComboRepository).save(testCombo);
    }
}
